# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release Package
on:
  release:
    types: [released]
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      - name: Install 💾
        run: npm ci

      - name: Version ⬆️
        run: npm version --new-version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Publish 🚂
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
